project:
  type: website
  output-dir: docs

website:
  title: "DS350_website_template"
  sidebar:
    style: floating
    contents:
      - index.qmd
      - text: "Week 1"
        href: weeks/week_one.qmd
      - text: "Week 2"
        href: weeks/week_two.qmd
      - text: "Week 3"
        href: weeks/week_three.qmd
      - text: "Week 4"
        href: weeks/week_four.qmd
      - text: "Week 5"
        href: weeks/week_five.qmd
      - text: "Week 6"
        href: weeks/week_six.qmd
      - text: "Week 7"
        href: weeks/week_seven.qmd
      - text: "Week 8"
        href: weeks/week_eight.qmd
      - text: "Week 9"
        href: weeks/week_nine.qmd
      - text: "Week 10"
        href: weeks/week_ten.qmd
      - text: "Week 11"
        href: weeks/week_eleven.qmd
      - text: "Week 12"
        href: weeks/week_twelve.qmd
      - text: "Week 13"
        href: weeks/week_thirteen.qmd


  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: project_page.qmd
        text: "Projects"
      - href: case_studies/gapminder1.qmd
        text: "Case Study"
      - href: task_manager.qmd
        text: "Tasks"
    right:
      - href: contact.qmd
        text: "Contact"
      - icon: github
        href: https://www.linkedin.com/in/jayton-crockett-ab585326a


format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    code-fold: true
    code-line-numbers: true

editor: visual

